import type {
  AggregationClause,
  MetricDisplay,
  MetricValueFormat,
} from "@pythia-software/query-table-core";
import type { MetricTheme } from "@pythia-software/query-table-ui";
const duration: MetricValueFormat = {
  kind: "duration",
  sourceUnit: "milliseconds",
  style: "human",
};
const metric = (
  id: string,
  label: string,
  display: MetricDisplay,
  expression: string,
  groupBy: string[] = [],
  width = 20,
  height = 12,
): AggregationClause => ({
  id,
  label,
  op: "count",
  expression,
  groupBy,
  display,
  layout: {
    widthRem: width,
    heightRem: height,
    minWidthRem: Math.min(width, 12),
    minHeightRem: Math.min(height, 6),
  },
});
export const DEMO_METRICS: AggregationClause[] = [
  metric("runs", "Runs in scope", { kind: "value" }, "COUNT()", [], 12, 7),
  metric(
    "pass-rate",
    "Pass rate",
    { kind: "value", format: { kind: "percent", decimals: 1 } },
    'SUM(IF([overall] = "PASS", 1, 0)) / NULLIF(COUNT(), 0)',
    [],
    12,
    7,
  ),
  metric(
    "latency",
    "Average duration",
    { kind: "value", format: duration },
    "AVG([total_ms])",
    [],
    14,
    7,
  ),
  metric(
    "platforms",
    "Platform mix",
    { kind: "donut", legendPosition: "right" },
    "COUNT()",
    ["platform"],
    24,
    13,
  ),
  metric(
    "pass-platform",
    "Pass rate by platform",
    {
      kind: "bar-horizontal",
      format: { kind: "percent", decimals: 1 },
      xLabel: "Share of runs",
    },
    'SUM(IF([overall] = "PASS", 1, 0)) / NULLIF(COUNT(), 0)',
    ["platform"],
    26,
    13,
  ),
  metric(
    "platform-duration",
    "Total duration by platform",
    { kind: "bar-vertical", format: duration, yLabel: "Total duration" },
    "SUM([total_ms])",
    ["platform"],
    24,
    13,
  ),
  metric(
    "worker-list",
    "Worker ranking",
    {
      kind: "list",
      list: { showBars: true, useGroupColors: true, showValues: true },
    },
    "COUNT()",
    ["worker"],
    20,
    12,
  ),
  metric(
    "status-pie",
    "Result distribution",
    { kind: "pie", legendPosition: "bottom" },
    "COUNT()",
    ["overall"],
    22,
    15,
  ),
  {
    ...metric(
      "scatter",
      "Throughput × duration",
      {
        kind: "scatter",
        xLabel: "Run count",
        yLabel: "Average duration",
        yFormat: duration,
        legendPosition: "bottom",
      },
      "COUNT()",
      ["worker"],
      26,
      14,
    ),
    expressionY: "AVG([total_ms])",
  },
  metric(
    "pivot",
    "Platform × result",
    { kind: "table" },
    "COUNT()",
    ["platform", "overall"],
    28,
    13,
  ),
  metric(
    "flat",
    "Platform × worker × result",
    { kind: "table" },
    "COUNT()",
    ["platform", "worker", "overall"],
    32,
    14,
  ),
  {
    ...metric(
      "box",
      "Duration spread",
      { kind: "box", format: duration, boxMean: true },
      "AVG([total_ms])",
      ["platform"],
      28,
      14,
    ),
    distribution: { kind: "box", input: "[total_ms]", whiskers: "tukey" },
  },
  {
    ...metric(
      "histogram",
      "Duration histogram",
      { kind: "histogram", xFormat: duration, legendPosition: "bottom" },
      "COUNT()",
      ["platform"],
      30,
      14,
    ),
    distribution: { kind: "histogram", input: "[total_ms]", bins: 10 },
  },
  {
    ...metric(
      "shown",
      "Runs on this page",
      { kind: "value" },
      "COUNT()",
      [],
      14,
      7,
    ),
    scope: "shownRows",
  },
  metric(
    "worker-line",
    "Run duration trend",
    {
      kind: "line",
      format: duration,
      xLabel: "Run",
      yLabel: "Average duration",
    },
    "AVG([total_ms])",
    ["id"],
    26,
    12,
  ),
];
export const DEMO_METRIC_THEME: MetricTheme = {
  layers: [
    { id: "platforms", colors: ["#0969da", "#8250df", "#1a7f37"] },
    {
      id: "results",
      colors: [
        "var(--qt-pass-fg, #1a7f37)",
        "var(--qt-fail-fg, #d1242f)",
        "#bf8700",
        "#8c959f",
      ],
    },
    { id: "workers", colors: ["#007c91", "#598234", "#b36200", "#7e5bef"] },
  ],
  dimensions: {
    platform: { layer: "platforms", domain: ["linux", "macos", "windows"] },
    overall: {
      layer: "results",
      domain: ["PASS", "FAIL", "DIFFERENCES", null],
    },
    worker: {
      layer: "workers",
      domain: ["worker-1", "worker-2", "worker-3", "worker-4"],
    },
  },
};
