import type {
  AggregationClause,
  MetricDisplay,
  MetricValueFormat,
  QueryState,
} from "@pythia-software/query-table-core";
const duration: MetricValueFormat = {
  kind: "duration",
  sourceUnit: "milliseconds",
  style: "human",
};
const percent: MetricValueFormat = { kind: "percent", decimals: 1 };
const ratio = 'SUM(IF([overall] = "PASS", 1, 0)) / NULLIF(COUNT(), 0)';
function card(
  id: string,
  label: string,
  expression: string,
  display: MetricDisplay,
  groupBy: string[] = [],
  widthRem = 22,
  heightRem = 13,
): AggregationClause {
  return {
    id,
    label,
    op: "count",
    expression,
    groupBy,
    scope: "allMatching",
    groupLimit: 100,
    display,
    layout: {
      widthRem,
      heightRem,
      minWidthRem: Math.min(widthRem, 12),
      minHeightRem: 6,
    },
  };
}
export const POSTGRES_METRICS: AggregationClause[] = [
  card("pg-runs", "All matching runs", "COUNT()", { kind: "value" }, [], 13, 7),
  {
    ...card(
      "pg-page",
      "Runs on this page",
      "COUNT()",
      { kind: "value" },
      [],
      13,
      7,
    ),
    scope: "shownRows",
  },
  card(
    "pg-pass",
    "Pass rate",
    ratio,
    { kind: "value", format: percent },
    [],
    13,
    7,
  ),
  card(
    "pg-duration",
    "Average duration",
    "AVG([total_ms])",
    { kind: "value", format: duration },
    [],
    15,
    7,
  ),
  card(
    "pg-queue",
    "Average queue wait",
    "AVG([queue_ms])",
    { kind: "value", format: duration },
    [],
    15,
    7,
  ),
  card(
    "pg-os",
    "Platform mix",
    "COUNT()",
    { kind: "donut", legendPosition: "right" },
    ["platform"],
    24,
    13,
  ),
  card(
    "pg-result",
    "Result mix",
    "COUNT()",
    { kind: "pie", legendPosition: "bottom" },
    ["overall"],
    22,
    14,
  ),
  card(
    "pg-os-duration",
    "Duration by platform",
    "AVG([total_ms])",
    { kind: "bar-vertical", format: duration, yLabel: "Mean duration" },
    ["platform"],
    24,
    14,
  ),
  card(
    "pg-os-pass",
    "Pass rate by platform",
    ratio,
    { kind: "bar-horizontal", format: percent, xLabel: "Share of runs" },
    ["platform"],
    25,
    14,
  ),
  {
    ...card(
      "pg-workers",
      "Busiest workers",
      "COUNT()",
      {
        kind: "list",
        list: { showBars: true, useGroupColors: true, showValues: true },
      },
      ["worker"],
      21,
      16,
    ),
    groupLimit: 12,
  },
  card(
    "pg-band",
    "Computed duration bands",
    "COUNT()",
    {
      kind: "list",
      list: { showBars: false, useGroupColors: true, showValues: true },
    },
    ["@computed/duration_band"],
    22,
    12,
  ),
  {
    ...card(
      "pg-trend",
      "Daily duration by platform",
      "AVG([total_ms])",
      {
        kind: "line",
        format: duration,
        xLabel: "Day (UTC)",
        yLabel: "Mean duration",
      },
      ["run_day", "platform"],
      36,
      16,
    ),
    sort: [
      { key: "group0", dir: "asc" },
      { key: "group1", dir: "asc" },
    ],
    groupLimit: 180,
  },
  {
    ...card(
      "pg-scatter",
      "Worker volume × duration",
      "COUNT()",
      {
        kind: "scatter",
        xLabel: "Run count",
        yLabel: "Mean duration",
        yFormat: duration,
        legendPosition: "none",
      },
      ["worker"],
      28,
      15,
    ),
    expressionY: "AVG([total_ms])",
  },
  card(
    "pg-pivot",
    "Platform × result",
    "COUNT()",
    { kind: "table" },
    ["platform", "overall"],
    28,
    14,
  ),
  {
    ...card(
      "pg-flat",
      "Platform × worker × result",
      "COUNT()",
      { kind: "table" },
      ["platform", "worker", "overall"],
      32,
      17,
    ),
    groupLimit: 40,
  },
  {
    ...card(
      "pg-box",
      "Duration spread · Tukey",
      "AVG([total_ms])",
      { kind: "box", format: duration, boxMean: true },
      ["platform"],
      30,
      15,
    ),
    distribution: { kind: "box", input: "[total_ms]", whiskers: "tukey" },
  },
  {
    ...card(
      "pg-queue-box",
      "Queue spread · min/max",
      "AVG([queue_ms])",
      { kind: "box", format: duration },
      ["platform"],
      28,
      15,
    ),
    distribution: { kind: "box", input: "[queue_ms]", whiskers: "minmax" },
  },
  {
    ...card(
      "pg-histogram",
      "Duration histogram",
      "COUNT()",
      { kind: "histogram", xFormat: duration, legendPosition: "bottom" },
      ["platform"],
      36,
      16,
    ),
    distribution: { kind: "histogram", input: "[total_ms]", bins: 20 },
  },
  {
    ...card(
      "pg-throughput",
      "Throughput by worker (computed)",
      "AVG([@computed/throughput])",
      {
        kind: "bar-horizontal",
        format: { kind: "number", decimals: 1 },
        xLabel: "Mean MB/s",
      },
      ["worker"],
      28,
      17,
    ),
    groupLimit: 12,
  },
  card(
    "pg-latest",
    "Latest run",
    "MAX([enqueued_at])",
    {
      kind: "value",
      format: {
        kind: "datetime",
        sourceUnit: "iso",
        style: "human",
        timeZone: "UTC",
      },
    },
    [],
    26,
    8,
  ),
];
export const POSTGRES_INITIAL_QUERY: QueryState = {
  select: [
    "id",
    "job_name",
    "platform",
    "overall",
    "total_ms",
    "@computed/throughput",
    "worker",
    "enqueued_at",
  ].map((field) => ({ field })),
  where: [],
  orderBy: [{ field: "enqueued_at", dir: "desc", nulls: "last" }],
  limit: 100,
  offset: 0,
  aggregations: POSTGRES_METRICS,
};
